import {
  Box,
  Button,
  ButtonGroup,
  Card,
  CardBody,
  Flex,
  Heading,
  HStack,
  Image,
  Stack,
  Text,
  SimpleGrid,
  
} from "@chakra-ui/react";
import { SocialIcon } from "react-social-icons";

import React from "react";
import skillsImage from "../asset/projects.png";
import { motion } from "framer-motion";
import { useEffect } from "react";
import AirIq from "../asset/ProjectsImages/airiq.png";
import HealthEase from "../asset/ProjectsImages/HealthEase.png";
import Talkative from "../asset/ProjectsImages/Talkative.png";
const Projects = () => {
  // useEffect(() => {
  //   // 👇️ scroll to top on page load
  //   window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
  // }, []);
  document.title = "Aditya Paliwal : Full Stack Developer";

  const animations = {
    div: {
      initial: {
        y: "100%",
        opacity: 0,
      },
      whileInView: {
        y: "0",
        opacity: 1,
      },
      transition: {
        duration: 0.5,
        behavior: "smooth",
      },
    },
    headdiv: {
      initial: {
        y: "100%",
        opacity: 0,
      },
      whileInView: {
        y: "0",
        opacity: 1,
      },
      transition: {
        duration: 0.5,
        delay: 0.5,
      },
    },
    home: {
      initial: {
        opacity: 0,
      },
      whileInView: {
        opacity: 1,
      },
      transition: {
        duration: 1.2,
      },
    },
  };

  return (
    <Box id="projects">
      <motion.div {...animations.div}>
        <Flex>
          <HStack
            align={"center"}
            justify={"space-between"}
            w={{ base: "80%", sm: "50%", md: "100%" }}
            gap={{ base: 20, md: 30 }}
            p={{ base: 5, md: 8 }}
          >
            <Heading
              w={{ base: "30%", sm: "50%", md: "90%" }}
              fontSize={{ base: "2xl", md: "5xl" }}
              fontFamily={"Kanit"}
              fontWeight={"bold"}
              bgGradient="linear(to-l,#4BA4A6, #1D4646 )"
              bgClip="text"
              ml={"7"}
            >
              Projects
            </Heading>

            <Box
              w={{ base: "70%", sm: "60%", md: "20%" }}
              mr={{ base: 0, md: 5 }}
            >
              <Image src={skillsImage} />
            </Box>
          </HStack>
        </Flex>
      </motion.div>

      <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} spacing={7} p={3}>
        <Card maxW="sm" height="md">
          <CardBody>
            <Image
              src={AirIq}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="3" spacing="2">
              <Heading size="md" textAlign={"center"}>
                AirIQ
              </Heading>
              <Text fontSize="sm">
                Our project is aimed at detecting the amount or concentration of
                different types of gases like carbon monoxide, butane etc. in
                the gas generated by waste like sewage water etc. We aim to
                provide an efficient and cost-effective solution for monitoring
                gas emissions in waste management facilities.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="1">
              <a href="https://airiq.us" >
                <Button
                  variant="solid"
                  colorScheme="blue"
                  bgGradient="linear(to-l,#4BA4A6, #1D4646 ) "
                  padding={"10px"}
                  width={"100%"}
                  color={"white"}
                  _hover={{
                    bg: "#1D4646",
                  }}
                >
                  Live
                </Button>
              </a>
              <a
                href="https://github.com/adityapaliwal1/AirIQ-Wittyhacks-1"
                
              >
                <Button bg={"none"}>
                  <SocialIcon
                    network="github"
                    style={{
                      height: "15px",
                      width: "15px",
                      marginRight: "6px",
                    }}
                  />{" "}
                  View Source
                </Button>
              </a>
            </ButtonGroup>
          </CardBody>
        </Card>

        <Card maxW="sm" height="md">
          <CardBody>
            <Image
              src={HealthEase}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="10" spacing="2">
              <Heading size="md" textAlign={"center"}>
                HealthEase
              </Heading>
              <Text fontSize={"sm"} textAlign={"left"}>
                HealthEase is a device that monitors health by measuring body
                parameters. Placed in public areas, users insert a coin to get
                health results on a web page. If abnormalities are detected, an
                alert is sent to the nearest hospital.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="1">
              <a href="https://healthease.ashutosh7i.dev" >
                <Button
                  variant="solid"
                  colorScheme="blue"
                  bgGradient="linear(to-l,#4BA4A6, #1D4646 ) "
                  padding={"10px"}
                  width={"100%"}
                  color={"white"}
                  _hover={{
                    bg: "#1D4646",
                  }}
                >
                  Live
                </Button>
              </a>
              <a
                href="https://github.com/adityapaliwal1/my-app"
                
              >
                <Button bg={"none"}>
                  <SocialIcon
                    network="github"
                    style={{
                      height: "15px",
                      width: "15px",
                      marginRight: "6px",
                    }}
                  />{" "}
                  View Source
                </Button>
              </a>
            </ButtonGroup>
          </CardBody>
        </Card>

        {/* <Card maxW="sm" height="md">
          <CardBody>
            <Image
              src={HealthEase}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="10" spacing="2">
              <Heading size="md" textAlign={"center"}>
                VoteChain
              </Heading>
              <Text fontSize={"sm"}>
                VoteChain is an innovative voting system designed to modernize
                and secure the democratic process using blockchain, IoT, and
                RFID technologies. By leveraging these cutting-edge tools,
                VoteChain ensures transparency, security, and efficiency in
                elections.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="1">
              <a href="https://healthease.ashutosh7i.dev" >
                <Button
                  variant="solid"
                  colorScheme="blue"
                  bgGradient="linear(to-l,#4BA4A6, #1D4646 ) "
                  padding={"10px"}
                  width={"100%"}
                  color={"white"}
                  _hover={{
                    bg: "#1D4646",
                  }}
                >
                  Live
                </Button>
              </a>
              <a
                href="https://github.com/adityapaliwal1/my-app"
               
              >
                <Button bg={"none"}>
                  <SocialIcon
                    network="github"
                    style={{
                      height: "15px",
                      width: "15px",
                      marginRight: "6px",
                    }}
                  />{" "}
                  View Source
                </Button>
              </a>
            </ButtonGroup>
          </CardBody>
        </Card> */}

        <Card maxW="sm" height="md" >
          <CardBody>
            <Image
              src={Talkative}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="10" spacing="2">
              <Heading size="md" textAlign={"center"}>
                Talk-a-tive
              </Heading>
              <Text fontSize={"sm"}>
                Talk-a-tive is a Full Stack Chatting App. Uses Socket.io for
                real time communication and stores user details in encrypted
                format in Mongo DB Database.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="1">
              <a
                href="https://talk-a-tive-7fgq.onrender.com/chats"
                
              >
                <Button
                  variant="solid"
                  colorScheme="blue"
                  bgGradient="linear(to-l,#4BA4A6, #1D4646 ) "
                  padding={"10px"}
                  width={"100%"}
                  color={"white"}
                  _hover={{
                    bg: "#1D4646",
                  }}
                >
                  Live
                </Button>
              </a>
              <a
                href="https://github.com/adityapaliwal1/Chat-app"
                
              >
                <Button bg={"none"}>
                  <SocialIcon
                    network="github"
                    style={{
                      height: "15px",
                      width: "15px",
                      marginRight: "6px",
                    }}
                  />{" "}
                  View Source
                </Button>
              </a>
            </ButtonGroup>
          </CardBody>
        </Card>

        {/* <Card maxW="sm" height="md">
          <CardBody>
            <Image
              src={AirIq}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="3" spacing="2">
              <Heading size="md">Living room Sofa</Heading>
              <Text>
                This sofa is perfect for modern tropical spaces, baroque
                inspired spaces, earthy toned spaces and for people who love a
                chic design with a sprinkle of vintage design.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="2">
              <Button variant="solid" colorScheme="blue">
                Buy now
              </Button>
              <Button variant="ghost" colorScheme="blue">
                Add to cart
              </Button>
            </ButtonGroup>
          </CardBody>
        </Card>

        <Card maxW="sm" height="md">
          <CardBody>
            <Image
              src={AirIq}
              alt="Green double couch with wooden legs"
              borderRadius="lg"
            />
            <Stack my="3" spacing="2">
              <Heading size="md">Living room Sofa</Heading>
              <Text fontSize="sm">
                Our project is aimed at detecting the amount or concentration of
                different types of gases like carbon monoxide, butane etc. in
                the gas generated by waste like sewage water etc. We aim to
                provide an efficient and cost-effective solution for monitoring
                gas emissions in waste management facilities.
              </Text>
            </Stack>
            <ButtonGroup spacing="2" mt="1">
              <Button variant="solid" colorScheme="blue">
                Buy now
              </Button>
              <Button variant="ghost" colorScheme="blue">
                Add to cart
              </Button>
            </ButtonGroup>
          </CardBody>
        </Card> */}
      </SimpleGrid>
    </Box>
  );
};

export default Projects;
